### ISSUE TITLE
Obrazovka "Přehled Hráčů"

### ISSUE THREAD

**Issue by vitgerza** [alesre77/mg_result_portal#4]
zde bych ještě udělal vyhledávání / seřazení i dle klubu

**Comment by alesre77** [comment]
ano vyhledávání pomocí klubu, viz listbox vlevo nahoře - výběr klubu ze seznamu. řazení dle klubu ok, doplnil jsem do popisu

**Comment by alesre77** [comment]
tím bych to tedy uzavřel. když tak otevřeme znovu
