### ISSUE TITLE
číselník povrchů - C_COURSE_TYPE

### ISSUE THREAD

**Issue by alesre77** [alesre77/mg_result_portal#5]
jak budeme označovat povrchy? E/B/F/MOS? nebo MTG/MG/F/MOS? nebo jinak, takto budou označeny i při kombi turnajích jednotlivá kola.

**Comment by vitgerza** [comment]
při výběru u pořadatele bych nechal povrchy jak jsou MTG / MG / FG / AG, na to jsou zvyklí. Při označování kol bych asi použil zkratky jak je na mezinárodních turnajích E / C / F / A

**Comment by alesre77** [comment]
ok
